{% set name = "looker-sdk" %}
{% set version = "25.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/looker_sdk-{{ version }}.tar.gz
  sha256: a35a1847ed7a04ca5a300cc9e314be3a1f6b9412fabaa465c178b1eddd190840

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - attrs >=20.1.0
    - cattrs >=1.3
    - requests >=2.22
    - typing_extensions >=4.1.1

test:
  imports:
    - looker_sdk
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.python.org/pypi/looker_sdk
  summary: Looker REST API
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/looker-open-source/sdk-codegen/tree/main/python

extra:
  recipe-maintainers:
    - xylar
