{% set name = "looker-sdk" %}
{% set version = "24.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/looker_sdk-{{ version }}.tar.gz
  sha256: de6e2b8beca5345e3538ea0d90c1044381e2c228d068aff372af0b1ff19313e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools

  run:
    - python >=3.7
    - attrs >=20.1.0
    - cattrs >=1.3
    - requests >=2.22
    - typing_extensions >=4.1.1

test:
  imports:
    - looker_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/looker_sdk
  summary: Looker REST API
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/looker-open-source/sdk-codegen/tree/main/python

extra:
  recipe-maintainers:
    - xylar
