{% set name = "looker-sdk" %}
{% set version = "24.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/looker_sdk-{{ version }}.tar.gz
  sha256: 4c23ec8687bdb29358e7c96656d53954172f6146e559f896023d711c3c7fa216

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    
  run:
    - python >=3.7
    - attrs >=20.1.0
    - cattrs >=1.3
    - requests >=2.22
    - typing-extensions >=4.1.1

test:
  imports:
    - looker_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/looker_sdk
  summary: Looker REST API
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
