schema_version: 1

context:
  name: looker-sdk
  version: 26.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/looker_sdk-${{ version }}.tar.gz
  sha256: 58a285021155c341078267c4890e1fa0e78e114fd75f10b1e41863e9bbcfec71

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - attrs >=20.1.0
    - cattrs >=1.3
    - requests >=2.22
    - typing_extensions >=4.1.1

tests:
  - python:
      imports:
        - looker_sdk
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: Looker REST API
  license: MIT
  license_file: LICENSE.txt
  homepage: https://pypi.python.org/pypi/looker_sdk
  repository: https://github.com/looker-open-source/sdk-codegen/tree/main/python

extra:
  recipe-maintainers:
    - xylar
